// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ_YlOCZn7zp-MS_V4N4X7_wm24ddfD70',
    appId: '1:65841628745:android:d154fad6aa4ba3fe142198',
    messagingSenderId: '65841628745',
    projectId: 'makhub-f2223',
    storageBucket: 'makhub-f2223.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd8hnJxAO9nODc7PcOcTrwCW-u1EdvmcA',
    appId: '1:65841628745:web:b39fd11f2c29dbea142198',
    messagingSenderId: '65841628745',
    projectId: 'makhub-f2223',
    authDomain: 'makhub-f2223.firebaseapp.com',
    storageBucket: 'makhub-f2223.firebasestorage.app',
    measurementId: 'G-2L5XN06C98',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE5MDURcO1Iy6U-Qju2iGnh1NclGIKfhA',
    appId: '1:65841628745:ios:5b07d63bd5a01012142198',
    messagingSenderId: '65841628745',
    projectId: 'makhub-f2223',
    storageBucket: 'makhub-f2223.firebasestorage.app',
    iosBundleId: 'com.example.makhub',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE5MDURcO1Iy6U-Qju2iGnh1NclGIKfhA',
    appId: '1:65841628745:ios:5b07d63bd5a01012142198',
    messagingSenderId: '65841628745',
    projectId: 'makhub-f2223',
    storageBucket: 'makhub-f2223.firebasestorage.app',
    iosBundleId: 'com.example.makhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd8hnJxAO9nODc7PcOcTrwCW-u1EdvmcA',
    appId: '1:65841628745:web:e63e696a95bfafda142198',
    messagingSenderId: '65841628745',
    projectId: 'makhub-f2223',
    authDomain: 'makhub-f2223.firebaseapp.com',
    storageBucket: 'makhub-f2223.firebasestorage.app',
    measurementId: 'G-F20XDW17WY',
  );
}
